before_script:
  - "bundle exec rake test_app"
script:
  - "bundle exec rspec spec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - jruby-20mode
  - rbx-2
env:
  - DB=sqlite
language: ruby
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-20mode
notifications:
  recipients:
    - swrobel@gmail.com
